project:
  type: website

website:
  title: "Welcome to my blog!"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/thinam-tamang/
      - icon: github
        href: https://github.com/ThinamXx
      - icon: gear-fill
        href: https://linktr.ee/Thinam
      - icon: twitter
        href: https://twitter.com/thinam_
format:
  html:
    theme: lux
    css: styles.css



